spring:
  application:
    name: camel-jpa-tn
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3305/tender?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgres:
      url: jdbc:postgresql://localhost:5432/test
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

logging:
  level:
    root: INFO
    com.jojolaptech.camel: INFO
    org.apache.camel: INFO
    org:
      hibernate:
        SQL: INFO
      apache:
        camel:
          component:
            jpa: INFO

camel:
  springboot:
    main-run-controller: true
  component:
    jpa:
      transaction-manager: "#mysqlTransactionManager"

